### ISSUE TITLE
Endermites

### ISSUE THREAD

**Issue by spiderm3n** [PoleisMC/Roadmap#48]
Revert the change made to endermites (deleing them every minute). Your reasoning behind it was "its an exploit", which in my opinion is not a valid reason. Endermites are a vanilla mechanic and should remain ion the server.

**Comment by WassimBenAzzoun** [comment]
IG name: TreywayTN
And please reconsider the VoidChaos reset. I don't think it's a valid reason to reset people's experience points and money because it's not balanced compared to 80% of players. First of all, the VoidChaos job is the only thing that can be done in it, which is farming Enderman. That's why most players are at low levels in it because it's not a passive job; you don't need to farm Enderman to obtain important resources. On the other hand, other jobs are semi-passive; you do them to get your needed resources. That's why the experience points for other jobs are balanced, but VoidChaos is not.

**Comment by Bushpeng** [comment]
After the rebalance and job payout limitations - endermites are no longer killed off by the server. The alterations to exp and income will remain as it was.
